version: '3'

services:
  db:
    build: ./infrastructure/db/postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market
    volumes:
      - ./infrastructure/db/postgres/data:/data

  market:
    build: ./market-api
    container_name: market
    environment:
      - DB_DRIVER_NAME=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=market
      - DB_SSL_MODE=disable
    depends_on:
      - db
    ports:
      - "1323:1323"