version: '3'

services:
  db-postgres:
    build: ./db/postgres
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market
    volumes:
      - ./db/postgres/data:/data
